helptags ~/.vim/bundle/Conque-Shell/doc
helptags ~/.vim/bundle/LeaderF/doc
helptags ~/.vim/bundle/YouCompleteMe/doc
helptags ~/.vim/bundle/ag.vim/doc
helptags ~/.vim/bundle/color-schemes/doc
helptags ~/.vim/bundle/ctrlp.vim/doc
helptags ~/.vim/bundle/dbext.vim/doc
helptags ~/.vim/bundle/lusty/doc
helptags ~/.vim/bundle/molokai/doc
helptags ~/.vim/bundle/nerdcommenter/doc
helptags ~/.vim/bundle/nerdtree/doc
helptags ~/.vim/bundle/simple_bookmarks.vim/doc
helptags ~/.vim/bundle/tagbar/doc
helptags ~/.vim/bundle/tslime.vim/doc
helptags ~/.vim/bundle/unite.vim/doc
helptags ~/.vim/bundle/vim-airline/doc
helptags ~/.vim/bundle/vim-colors-solarized/doc
helptags ~/.vim/bundle/vim-easymotion/doc
helptags ~/.vim/bundle/vim-monokai/doc
helptags ~/.vim/bundle/vim-pathogen/doc
helptags ~/.vim/bundle/vim-railscasts-theme/doc
helptags ~/.vim/bundle/vim-tmux-navigator/doc
helptags ~/.vim/bundle/vimproc.vim/doc
